//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Arithmetic.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ArithmeticNamespace {

#pragma warning disable 3021

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ArithmeticLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, REG=3, INT=4, MUL=5, DIV=6, ADD=7, SUB=8, WS=9;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "REG", "INT", "MUL", "DIV", "ADD", "SUB", "WS"
	};


	    protected const int EOF = Eof;
	    protected const int HIDDEN = Hidden;


	public ArithmeticLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ArithmeticLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", null, null, "'*'", "'/'", "'+'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "REG", "INT", "MUL", "DIV", "ADD", "SUB", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Arithmetic.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ArithmeticLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\v', '\x34', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x6', '\x4', '\x1C', '\n', '\x4', '\r', '\x4', '\xE', '\x4', '\x1D', 
		'\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\"', '\n', '\x5', '\x3', '\x5', 
		'\x6', '\x5', '%', '\n', '\x5', '\r', '\x5', '\xE', '\x5', '&', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x2', '\x2', '\v', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x3', '\x2', '\x5', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x5', '\x2', 
		'\x32', ';', '\x43', 'H', '\x63', 'h', '\x5', '\x2', '\f', '\f', '\xF', 
		'\xF', '\"', '\"', '\x2', '\x36', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x3', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x17', '\x3', '\x2', '\x2', '\x2', '\a', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\t', '!', '\x3', '\x2', '\x2', '\x2', '\v', '(', 
		'\x3', '\x2', '\x2', '\x2', '\r', '*', '\x3', '\x2', '\x2', '\x2', '\xF', 
		',', '\x3', '\x2', '\x2', '\x2', '\x11', '.', '\x3', '\x2', '\x2', '\x2', 
		'\x13', '\x30', '\x3', '\x2', '\x2', '\x2', '\x15', '\x16', '\a', '*', 
		'\x2', '\x2', '\x16', '\x4', '\x3', '\x2', '\x2', '\x2', '\x17', '\x18', 
		'\a', '+', '\x2', '\x2', '\x18', '\x6', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x1B', '\a', '%', '\x2', '\x2', '\x1A', '\x1C', '\t', '\x2', '\x2', '\x2', 
		'\x1B', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x1E', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', ' ', '\a', '\x32', '\x2', '\x2', ' ', '\"', '\a', 'z', '\x2', 
		'\x2', '!', '\x1F', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\x3', '\x2', 
		'\x2', '\x2', '\"', '$', '\x3', '\x2', '\x2', '\x2', '#', '%', '\t', '\x3', 
		'\x2', '\x2', '$', '#', '\x3', '\x2', '\x2', '\x2', '%', '&', '\x3', '\x2', 
		'\x2', '\x2', '&', '$', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\n', '\x3', '\x2', '\x2', '\x2', '(', ')', 
		'\a', ',', '\x2', '\x2', ')', '\f', '\x3', '\x2', '\x2', '\x2', '*', '+', 
		'\a', '\x31', '\x2', '\x2', '+', '\xE', '\x3', '\x2', '\x2', '\x2', ',', 
		'-', '\a', '-', '\x2', '\x2', '-', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'.', '/', '\a', '/', '\x2', '\x2', '/', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'\x30', '\x31', '\t', '\x4', '\x2', '\x2', '\x31', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '\x33', '\b', '\n', '\x2', '\x2', '\x33', '\x14', 
		'\x3', '\x2', '\x2', '\x2', '\a', '\x2', '\x1B', '\x1D', '!', '&', '\x3', 
		'\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace ArithmeticNamespace
