//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Assembler.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AssemblerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IAssemblerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] AssemblerParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] AssemblerParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] AssemblerParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.opcode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpcode([NotNull] AssemblerParser.OpcodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.register_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegister_([NotNull] AssemblerParser.Register_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirective([NotNull] AssemblerParser.DirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.assemblerdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblerdirective([NotNull] AssemblerParser.AssemblerdirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.lbl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLbl([NotNull] AssemblerParser.LblContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.expressionlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionlist([NotNull] AssemblerParser.ExpressionlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] AssemblerParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] AssemblerParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.arithop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithop([NotNull] AssemblerParser.ArithopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.unaryop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryop([NotNull] AssemblerParser.UnaryopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] AssemblerParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.dollar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDollar([NotNull] AssemblerParser.DollarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] AssemblerParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] AssemblerParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] AssemblerParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AssemblerParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] AssemblerParser.CommentContext context);
}
