using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace M68HC11
{
    public class OpcodesAddressingModes
    {
        private static AM[] amOpcode =
            {
        /*00     01     02     03     04     05     06     07     08     09     0A     0B     0C     0D     0E     0F*/
          AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH, /* 00 */
          AM.INH,AM.INH,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INX,AM.INX,AM.INX,AM.INX, /* 10 */
          AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL, /* 20 */
          AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH, /* 30 */
          AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH, /* 40 */
          AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH, /* 50 */
          AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX, /* 60 */
          AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT, /* 70 */
          AM.IM1,AM.IM1,AM.IM1,AM.IM2,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM2,AM.IM1,AM.IM2,AM.IM1, /* 80 */
          AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR, /* 90 */
          AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX, /* a0 */
          AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT, /* b0 */
          AM.IM1,AM.IM1,AM.IM1,AM.IM2,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM2,AM.IM1,AM.IM2,AM.IM1, /* c0 */
          AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DIR, /* d0 */
          AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX, /* e0 */
          AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT  /* f0 */
        };



        //      private static AM[] opmodes =
        //{
        /*00     01     02     03     04     05     06     07     08     09     0A     0B     0C     0D     0E     0F*/
        //AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.ILL,AM.INH,AM.INH,AM.INH,AM.INH, /* 00-0F */
        //AM.INH,AM.INH,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.INH,AM.INH,AM.ILL,AM.INH,AM.ILL,AM.INH,AM.INX,AM.INX,AM.INX,AM.INX, /* 10-1F */
        //AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL,AM.REL, /* 20-2F */
        //AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH, /* 30-3F */
        //AM.INH,AM.ILL,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.INH, /* 40-4F */
        //AM.INH,AM.ILL,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.INH,AM.INH,AM.INH,AM.INH,AM.INH,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.INH, /* 50-5F */
        //AM.INX,AM.ILL,AM.ILL,AM.INX,AM.INX,AM.ILL,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.ILL,AM.INX,AM.INX,AM.IXS,AM.INX, /* 60-6F */
        //AM.EXT,AM.ILL,AM.ILL,AM.EXT,AM.EXT,AM.ILL,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.ILL,AM.EXT,AM.EXT,AM.EXS,AM.EXT, /* 70-7F */
        //AM.IM1,AM.IM1,AM.IM1,AM.IM2,AM.IM1,AM.IM1,AM.IM1,AM.ILL,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM2,AM.REL,AM.IM2,AM.INH, /* 80-8F */
        //AM.DIR,AM.DIR,AM.DIR,AM.DI2,AM.DIR,AM.DIR,AM.DIR,AM.DIS,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DI2,AM.DIR,AM.DI2,AM.DIS, /* 90-9F */
        //AM.INX,AM.INX,AM.INX,AM.IX2,AM.INX,AM.INX,AM.INX,AM.IXS,AM.INX,AM.INX,AM.INX,AM.INX,AM.IX2,AM.INX,AM.IX2,AM.IXS, /* A0-AF */
        //AM.EXT,AM.EXT,AM.EXT,AM.EX2,AM.EXT,AM.EXT,AM.EXT,AM.EXS,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EX2,AM.EXT,AM.EX2,AM.EXS, /* B0-BF */
        //AM.IM1,AM.IM1,AM.IM1,AM.IM2,AM.IM1,AM.IM1,AM.IM1,0  ,AM.IM1,AM.IM1,AM.IM1,AM.IM1,AM.IM2,0,  AM.IM2,AM.INH, /* C0-CF */
        //AM.DIR,AM.DIR,AM.DIR,AM.DI2,AM.DIR,AM.DIR,AM.DIR,AM.DIS,AM.DIR,AM.DIR,AM.DIR,AM.DIR,AM.DI2,AM.DIS,AM.DI2,AM.DIS, /* D0-DF */
        //AM.INX,AM.INX,AM.INX,AM.IX2,AM.INX,AM.INX,AM.INX,AM.IXS,AM.INX,AM.INX,AM.INX,AM.INX,AM.IX2,AM.IXS,AM.IX2,AM.IXS, /* E0-EF */
        //AM.EXT,AM.EXT,AM.EXT,AM.EX2,AM.EXT,AM.EXT,AM.EXT,AM.EXS,AM.EXT,AM.EXT,AM.EXT,AM.EXT,AM.EX2,AM.EXS,AM.EX2,AM.EXS /* F0-FF */
        //        };

        public static AM LookupAM(byte opcode, byte preByte)
        {
            switch (preByte)
            {
                case 0: return amOpcode[opcode];
                case 0x18: return amOpcode_18[opcode];
                case 0x1a: return amOpcode_1a[opcode];
                case 0xcd: return amOpcode_cd[opcode];
                default:
                    throw new Exception();
            }
        }


        private static AM[] amOpcode_18 =
  {
/*00     01     02     03     04     05     06     07     08     09     0A     0B     0C     0D     0E     0F*/
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 00 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INY,AM.INY,AM.INY,AM.INY, /* 10 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 20 */
  AM.INH,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INH,AM.ILL,AM.ILL,AM.INH,AM.ILL,AM.INH,AM.ILL,AM.INH,AM.ILL,AM.ILL,AM.ILL, /* 30 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 40 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 50 */
  AM.INY,AM.ILL,AM.ILL,AM.INY,AM.INY,AM.ILL,AM.INY,AM.INY,AM.INY,AM.INY,AM.INY,AM.ILL,AM.INY,AM.INY,AM.INY,AM.INY, /* 60 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 70 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.IM2,AM.ILL,AM.ILL,AM.IM1, /* 80 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.DIR,AM.ILL,AM.ILL,AM.ILL, /* 90 */
  AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX, /* a0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.EXT,AM.ILL,AM.ILL,AM.ILL, /* b0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.IM2,AM.ILL, /* c0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.DIR,AM.DIR, /* d0 */
  AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX,AM.INX, /* e0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.EXT,AM.EXT  /* f0 */
        };






        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 00-0F */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.ILL,AM.INY,AM.INY,AM.INY,AM.INY, /* 10-1F */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INH,AM.INH,AM.ILL,AM.ILL,AM.INY,AM.INY,AM.INY,AM.INY, /* 20-2F */
        //AM.INH,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INH,AM.ILL,AM.ILL,AM.INH,AM.ILL,AM.INH,AM.ILL,AM.INH,AM.ILL,AM.ILL,AM.ILL, /* 30-3F */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 40-4F */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 50-5F */
        //AM.INY,AM.ILL,AM.ILL,AM.INY,AM.INY,AM.ILL,AM.INY,AM.INY,AM.INY,AM.INY,AM.INY,AM.ILL,AM.INY,AM.INY,AM.IYS,AM.INY, /* 60-6F */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 70-7F */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.IM2,AM.ILL,AM.ILL,AM.INH, /* 80-8F */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.DI2,AM.ILL,AM.ILL,AM.ILL, /* 90-9F */
        //AM.INY,AM.INY,AM.INY,AM.IY2,AM.INY,AM.INY,AM.INY,AM.IYS,AM.INY,AM.INY,AM.INY,AM.INY,AM.IY2,AM.INY,AM.IY2,AM.IYS, /* a0-aF */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.EX2,AM.ILL,AM.ILL, /* b0-bF */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.IM2,AM.ILL, /* c0-cF */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.DI2,AM.DIS, /* d0-dF */
        //AM.INY,AM.INY,AM.INY,AM.IY2,AM.INY,AM.INY,AM.INY,AM.IYS,AM.INY,AM.INY,AM.INY,AM.INY,AM.IY2,AM.IYS,AM.IY2,AM.IYS, /* e0-eF */
        //AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.EX2,AM.EXS /* f0-fF */
        //        };

        private static AM[] amOpcode_1a = new AM[]
{
/*00     01     02     03     04     05     06     07     08     09     0A     0B     0C     0D     0E     0F*/
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 00 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 10 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 20 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 30 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 40 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 50 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 60 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 70 */
  AM.ILL,AM.ILL,AM.ILL,AM.IM2,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 80 */
  AM.ILL,AM.ILL,AM.ILL,AM.DIR,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 90 */
  AM.ILL,AM.ILL,AM.ILL,AM.INX,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INX,AM.ILL,AM.ILL,AM.ILL, /* a0 */
  AM.ILL,AM.ILL,AM.ILL,AM.EXT,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* b0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* c0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* d0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INX,AM.INX, /* e0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL  /* f0 */
};








        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 00-0F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 10-1F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 20-2F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 30-3F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 40-4F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 50-5F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 60-6F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 70-7F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.IM2,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 80-8F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.DI2,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 90-9F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.IX2,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INX,AM.ILL,AM.ILL,AM.ILL, /* a0-aF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.EX2,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* b0-bF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* c0-cF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* d0-dF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.IX2,AM.IX2, /* e0-eF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* f0-fF */
        //};

        private static AM[] amOpcode_cd = {
/*00     01     02     03     04     05     06     07     08     09     0A     0B     0C     0D     0E     0F*/
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 00 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 10 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 20 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 30 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 40 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 50 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 60 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 70 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 80 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 90 */
  AM.ILL,AM.ILL,AM.ILL,AM.INY,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INY,AM.ILL,AM.ILL,AM.ILL, /* a0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* b0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* c0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* d0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INY,AM.INY, /* e0 */
  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL  /* f0 */
        };

        //{
        ///*00     01     02     03     04     05     06     07     08     09     0A     0B     0C     0D     0E     0F*/
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 00-0F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 10-1F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 20-2F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 30-3F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 40-4F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 50-5F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 60-6F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 70-7F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 80-8F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* 90-9F */
        //  AM.ILL,AM.ILL,AM.ILL,AM.INY,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.INY,AM.ILL,AM.ILL,AM.ILL, /* a0-aF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* b0-bF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* c0-cF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* d0-dF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.IY2,AM.IYS, /* e0-eF */
        //  AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL,AM.ILL, /* f0-fF */
        //};
    }
}