using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Intel8085
{
    public enum MnemonicEnums : byte
    {
        aci = 0xce,
        adc = 0x88,
        add = 0x80,
        adi = 0xc6,
        ana = 0xa0,
        ani = 0xe6,
        arhl = 0x10,
        call = 0xcd,
        cc = 0xdc,
        cm = 0xfc,
        cma = 0x2f,
        cmc = 0x3f,
        cmp = 0xb8,
        cnc = 0xd4,
        cnz = 0xc4,
        cp = 0xf4,
        cpe = 0xec,
        cpi = 0xfe,
        cpo = 0xe4,
        cz = 0xcc,
        daa = 0x27,
        dad = 0x09,
        dcr = 0x05,
        dcx = 0x0b,
        dsub = 0x08,
        di = 0xf3,
        ei = 0xfb,
        hlt = 0x76,
        inA = 0xdb,
        inr = 0x04,
        inx = 0x03,
        jc = 0xda,
        jk = 0xfd,
        jm = 0xfa,
        jmp = 0xc3,
        jnc = 0xd2,
        jnk = 0xdd,
        jnz = 0xc2,
        jp = 0xf2,
        jpe = 0xea,
        jpo = 0xe2,
        jz = 0xca,
        lda = 0x3a,
        ldax = 0x0a,
        ldhi = 0x28,
        ldsi = 0x38,
        lhld = 0x2a,
        lhlx = 0xed,
        lxi = 0x01,
        mov = 0x40,
        mvi = 0x06,
        nop = 0x00,
        ora = 0xb0,
        ori = 0xf6,
        outA = 0xd3,
        pchl = 0xe9,
        pop = 0xc1,
        push = 0xc5,
        ral = 0x17,
        rar = 0x1f,
        rc = 0xd8,
        rdel = 0x18,
        ret = 0xc9,
        rim = 0x20,
        rlc = 0x07,
        rm = 0xf8,
        rnc = 0xd0,
        rnz = 0xc0,
        rp = 0xf0,
        rpe = 0xe8,
        rpo = 0xe0,
        rrc = 0x0f,
        rst = 0xc7,
        rstv = 0xcb,
        rz = 0xc8,
        sbb = 0x98,
        sbi = 0xde,
        shld = 0x22,
        shlx = 0xd9,
        sim = 0x30,
        sphl = 0xf9,
        sta = 0x32,
        stax = 0x02,
        stc = 0x37,
        sub = 0x90,
        sui = 0xd6,
        xchg = 0xeb,
        xra = 0xa8,
        xri = 0xee,
        xthl = 0xe3
    }
}